apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/haproxy-ingress
  prune: true
  dependsOn:
    - name: namespaces
    - name: cert-manager-certs
  sourceRef:
    kind: GitRepository
    name: flux-system