apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: namespaces
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/remu/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system