apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealedsecrets
  namespace: flux-system
spec:
  interval: 5m
  path: ./clusters/remu/secrets
  prune: true
  dependsOn:
    - name: namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system