---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: ghcr-creds
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgDFceOBFVs8oN1jkSi/O0TMSC838RbKUyfh6amoaeVR8f5PU6WvpNMydUD60xce34lUpM84E1d3Nt56wPuXp79m0Cotvo1a9VvaJaNe7uaz3oj43bJYKFtP6rNtK/eMassqguHnib3Fc/WHx+W41hJClxXcBEVqVifrfhabg5PJKEeSmqxgzyrLu+N/M0vCPDJQzpjt8YRo7+rUom1RRpC8VY+V6T6ckvC/oDUzpCnM2G71TsCwZr6vghvEsgxnHEYKuOescRv3X5zDDbWVQ/xuY3XU2urf1NGt1zuG/CD/eX9+c44Wc9uIb4BfcmZpU5uiMUnd7gzfIsyDhXebifdXyn220pgYJYiG5D9/Ekg/uyYEfNKUd1P3pHkUXX984WQfmMSxLt9FANo1b/vACAOvW55EZNr2JNNmnAblyOMktymeTmK/wnsSYq+vrqsclAYTExrsxts8ofBOiXxQNLJUxeq5tbXgOVtWVMPDJpOerR22yzYd4xMj8ZnqJeE0mDTGVnnMoSBZs3ttFNPlF0QiXJbix0Pe69L6AnIystv1M28307C2emabdKH6NxLLV7jD4XCXU7rdxUWmdW6B6o53+kJ/898IaIYCSXsLeGcYhD9gfrq3o48K9WfyH6L/sVWW6JDuiCs87a6x+CSa18HDmnXA+3e8ppOfBLdETVLMUHoY9LZlvHkwYv3jeJP4H6x47JPQILRNiE26iCt+sh5frP8wWLp0f39A9HAw7nbJUTRND78yxp1NRa7vcE4RdUsCv07oanwuepLM2w9SPAUidM4DbkINpzCYg5eoSX09OrCid0FjefXcsFrd0fSlfRB4JImGRA/0XmCKVgAjbPtzpUG07tcWur7xI3aS125m/5puKFm3/rWzuqPE908aBix0oERCu3q4eIFEKdggcvi+6Q8pKy0yAwlRrx4uZK02h0MG
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: ghcr-creds
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
