---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgC6FuJTa8+WafiMWrcSbMFYd6tmT0dcTTQ3uEYS4L9EA69GkViMHnOqldyMGjvyNZw00Qw8h3cQsUCxo8FSGQqwXfHIfCgCSEI1dCTjdV3ubS5NAy1J0A9T/CK9P0DOd5NnAVzekixgrBceoDZ6yfcO1eXTLA6YNbkgGzFvRgCB2iSkDxQe8qAEDxi0NOA2PrivFuYEktSlQLpkJzTirA8Fwj5ieX5pkgQvbMVEImQRpZdhD3tgJkCqH1fyAYvu+koifHE0wOCwmw24qKrwvXehT3J8noCZpL+t9Zh0t6vOEh8YLoIi5466wEWo3l3Jy1xV5yzVjwXCOCohjzBKKqOZwrDSVa+g0qxB/o5BddvV7jFJXnEQBNibp8j08n9xxgQ0GhAvCGQIqFtGzs+xf2vuVWrNiBLjBj0nvt6JzrRub5b9Fy0JcDUNqiKZ6Ig9KaEy5qZtI6F+IPQ2NLMPtEo1IMNJ1rzzk8Uc0LPsN2j7o4Cb9+O6gRktpMzJeBuCDJQjlnU4zljcVFyenGXDRgRiEqbZFh4N25ILZWl8XEOmzzRzgyCi9kfMwk0u+Mv9pt8LFsPgMYDaahPGdi5YsY9hH16DKPBpp136UVkZ61QIPToPvPZk3dyGV0/WyiKuWdr710rq9d/XX1MGonPE+YoUnREs+ril+sWd+lieQJXQrE/mx1FzFNu0COVJQE8YYZhrND0SKqhSpSYglVPLq1SNVqRHp2zvBKmh9un9Ky3jOjmm+t/Qp3z5
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
