apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/cert-manager"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system