---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBbT06zC4lH61f3O2qme1l+fzALwpxsJ5Py6JHiFUXcyh+OAVwQr/ddsbLlcTik0iHFdaUNlxxbuRRQ2ooXJHalZAFQZ0IFBdPHKuvw1WIAFt+pE0gRLWb5N1/UnsLMGxx9O3tPwjW1t7M3jFhlEJcIgc9LnaUlT9/daL6CICPU4Tz6OtuJqZuxqkBZm7eot8UQzjtYsjHOG2K66QReX0nnUMJEKGR8j7tx4RFRC4VzZZAl/gnvd+SMgHOI8iWs+BPVPkz7giwT56C4lCEUOSYDErNKWIqDFC0uFp7MoSLitjOvTrESxnymcJv5spGEdgyRvWFwvinwJ+gIobeJGlrPhCW/X92yWkGdy0oEtfMM6qjFAUZX5vICY5C1GI4gkjwNCf4VGuLNaHT1g7iPiPhQR8HIdmvv4wtess2kak3rnLZeaDbly9GFcHrPuTyy3TjaSqoxzoGlc7Wv2ncEn1sQR9pLmUa437Get8CBwjUvAgeioj9SqU0RDhe4jJgov2f3HIuaSv3G53eoFvvruDlC1ZJ0ks5i7O0GD8SSSXvvkN87K+g6enLjYOulKOZm0p8VsxIUivaTan2ycEFVjjc1N21w0LO7tOKh4nE/ECzc9aaMGmG5N8FM6cpISRhZIlrRS28ZqRcahRNtVC7ghQzYiw9qIk58wS3YG8IUBdVVUht5FfVqLR3SIdgZXiEwdPZk3ssP3XRWkmRf
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
