apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
      version: ">=6.0.0"
  values:
    persistence:
      enabled: true
      size: 5Gi
      accessModes:
        - ReadWriteOnce
      storageClassName: local-path
    admin:
      existingSecret: grafana-admin-secret  # tutaj odwołujesz się do swojego SealedSecret
    ingress:
      enabled: true
      hosts:
        - tmdev.pl
      paths:
        - /grafana
      tls: []
