---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAfTqSqev1GOVD5RfbxAtPJRCm1W+Q1opNBG6b4NJj+Mg+ErfwfK1dsvalDqYUTuJD9DqgFFP8R8VGgYLYtl8wBu878bt6nh1/hWerldu6a3ZZ7FjSKbddSjqVTLuHZEzm1Bg182CgCVlKXUkyQi3qFRg/HFNW3wJeMrhsaGw7edjjdUSdcQlcwRuIqYuFyrz/kHoFWuEjVzh/BZLZTKrQ1pSh3Z0EILtbnT0z6x7jdfZUmyahKVA6ZdE64HzA47igLW69DSSEouRxtcLXiOGzWkzBXhvo5Uwv1PIkZmICNQ8QtZJz+8HxjYXudLfoQR4mLV8GOJdXiSXvMTTFxAeFVuX3gI2AJXKZje/OYEpUtn55vu8Yjy4s7PGUmONxZ7QAM4UvHR0OYfunOdgbtSiVzyDaL3GODm7uf51AwABmFW6pdOx71q5zFV/WrDxPMND6FjGj9VFCkPcINjJdMlf55M+bVfSqMz6ug/55tE+9Fek8ZgwDkP7UMnxkCjGRPOOAyWDwLV0aEC1zpSsec+G5nZvFJE7KDSoHcCJGd+uS94ypg7XqjRPM0zzHEQZZ1Me6dEy7058scj+F5cM31NU54WGTSCV1atMpx5OSKE9NpaXpX3ScH3WgPqPfHsOm7AkBTpbUr0djf5Bp405pXOh8L94UMDIWo26CWdTIPBGCZhN2NJKsTJMPnPF4bGvLg4pcAlkOW9JjtjWKD
    admin-user: AgB8F+pRTGVphTKJKRiN17540xcv43sj55FjG1zpwQmdmpeNo2eIl74Pm4KQROREUk+ne0KqVgr1h1yp/CrVXnratSxiwb94p+0/URJe9vBuRJephnZv7wpjpUbzwZU1F5ZO+T6GcA+M+fQzbll2KGoG1TNjtqy5nppsiPbaFbGKNLPntg3+MCRmsOBhFEXK4qfZ/fBysq2LY8eKmpZab29E7SRU2gtVVbKuVlCVaRfhc1RMarRfY+KYxe68dxC5bIcd+4Yt0GzX849bMzDRnJsjWCn6sgnFya6O1M9AYn+1XNAQTm053mtCiAnqkbw6J8Lt3NWPnAJplCwyqDR894ERYoKWcQTaE2fvtsxVJ9nbkiA3+B8P4Zme0F99W+7PlNG2Wrzk4dCgfqaWRAqks7Pj5IayDhVe6O8RWhZimZPx+6LyAvENR1FviDWVCzqF9hkdgZvZExQpnTC6KZR/Nl6ZeFfMMPo3PG31ZXzCRBF8MeXKTiZqjUetv81qhS2gDuGw9aus9dfz0kJToLqYZwnA6Rdu7b8ORu8q0HW1qSzLk1W9G9FbB/xQq3tP3bzVUGnLFlonbNLs/+Xv/H/C5JNVTJszOYdllGvFSZ1cjAuemhRjOO3ElKnRlfIFePewlR9jjQP8C/0FPnZYztYJkQ77NcDtUkUKCm6hKzr8hjhUfAOC7m8p6R2Drvln5wuj7mIp9n/zVwJYxQg=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
