apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
spec:
  url: https://prometheus-community.github.io/helm-charts
  interval: 24h
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.15.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: true
      replicas: 1
      initChownData:
        enabled: false
      admin:
        existingSecret: grafana-admin-secret
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        ingressClassName: haproxy
        hosts:
          - grafana.tmdev.pl
        paths:
          - /
        servicePort: 80
        tls:
          - secretName: grafana-tmdev-tls
            hosts:
              - grafana.tmdev.pl
      service:
        type: ClusterIP
      persistence:
        enabled: true
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    prometheus:
      service:
        type: NodePort
        nodePort: 30900
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      enabled: false
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
