apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "75.15.0"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    grafana:
      enabled: true
      admin:
        existingSecret: grafana-admin-secret
        userKey: admin-user
        passwordKey: admin-password
      ingress:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
        path: /grafana(/|$)(.*)
        pathType: Prefix
        hosts:
          - tmdev.pl
        servicePort: 80
      service:
        type: ClusterIP
      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 5Gi
    prometheus:
      service:
        type: NodePort
        nodePort: 30900
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 10Gi
    alertmanager:
      enabled: false
    kubeStateMetrics:
      enabled: true
    nodeExporter:
      enabled: true
