apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/cert-manager/certs
  prune: true
  dependsOn:
    - name: cert-manager-issuers
  sourceRef:
    kind: GitRepository
    name: flux-system