apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/monitoring
  prune: true
  dependsOn:
    - name: namespaces
    - name: sealedsecrets
    - name: haproxy-ingress
  sourceRef:
    kind: GitRepository
    name: flux-system