apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: haproxy-ingress
  namespace: flux-system
spec:
  url: https://haproxy-ingress.github.io/charts
  interval: 24h

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: haproxy-ingress
  namespace: ingress-controller
spec:
  interval: 5m
  chart:
    spec:
      chart: haproxy-ingress
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: haproxy-ingress
        namespace: flux-system
  values:
    controller:
      ingressClass: haproxy
      ingressClassResource:
        enabled: true
        default: true
      kind: DaemonSet
      daemonset:
        useHostPort: true
      service:
        type: ClusterIP
      metrics:
        enabled: true
      serviceMonitor:
        enabled: true