apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certs
  namespace: flux-system
spec:
  dependsOn:
    - name: issuer
  interval: 5m
  path: "./apps/cert-manager/certs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system