name: Build and Publish bun-fiber

on:
  push:
    branches:
      - master
    paths:
      - 'apps/bun-fiber/backend/**'
      - 'apps/bun-fiber/frontend/**'
      - 'apps/bun-fiber/Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set timestamp tag
        id: vars
        run: echo "TIMESTAMP=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Build and push image with timestamp tag
        run: |
          echo "Tagging image with: $TIMESTAMP"
          docker build -f apps/bun-fiber/Dockerfile -t ghcr.io/${{ github.repository_owner }}/bun-fiber:$TIMESTAMP .
          docker push ghcr.io/${{ github.repository_owner }}/bun-fiber:$TIMESTAMP

  cleanup:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Cleanup old images - keep latest 5
        uses: snok/container-retention-policy@v3.0.0
        with:
          account: ${{ github.repository_owner }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "bun-fiber"
          keep-n-most-recent: 5