name: Build and Publish Docker image

on:
  push:
    branches:
      - master
    paths:
      - 'apps/bun-fiber/**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          docker build -f apps/bun-fiber/Dockerfile -t ghcr.io/${{ github.repository_owner }}/bun-fiber:latest ./apps/bun-fiber

      - name: Push the Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/bun-fiber:latest
