---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAW0nBflLdisfm09iggOr8pWraQBbuk+apIpwypcMhqsPzNnH0NoHx8NocEuW2LgPXpiPKONeZR297x+ByUkzY+vAXLy4OQtbBrtKEGBe6gBCYOl31gMWOYfGGmKkkLbGi0ADFn8G5kdILpFjQuxDK9PbR2hKCKqNjF4k19gUkGQ9zsPLJWqEvCE5bfPhGOhYiOgOZRYqb9W+5Eb4cG28/qgHH9G7SjDB+tFH9y9dQJi/dae+Y/05iq1BZqbbFIxtHt5hAL29hMYy6ibXMK6nCJH+xM+bNJPnGBwe+VlebSvAFfDXcc4PfktORM38VkvAwNSHyzAqdhDYxmQ5es8w6bXBWoxeAoAic3IsRGdhurKpaseo2LpG+8yqsAMQGeYi6GkZrla1pTU3IOPaEGUPRtriKb43GbCDWT2A/LAKSfuHPijGEXzl0Dxz7983j3+lk6enLonpfONMgAgxOs+F6R90vHUESp+So2uUd/rHHYEwMFzteZ9e1ERiiJmz5Mp+HdW5N2wLtzqWnTbRkygrT6SuJs0ZpVMlFDD+Nhw37/Ifl4MVOWBQTJADzjLp7QzYhVjgJfATjoNL0hfllGNgCTje2N08xaLdQy2Mo8cSC11MeRqTfhIvz8NZxavpYg/aAHasYo6tqC7c1ZT7MZiHfiy0qt8t2EmX+W9qxEI5FK8AQ1DVzGWhYsuQrQ8rXqwtuncNS1B5C4xZm2A2Tt09VcUtAWu6xw29qmWAh7AKJskujiJ6aNZ9sp
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
