---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCijrWfjPfOc/z1z5itawetuXHHwcX6iS7zrj+Kr5GVO5UNyKZ9Hb7alaBIebqsMqMKijMnSvWtcJYgpVjbJh5lyjCfeoMAn+tjVh64PwOA9suA3oW4dyQtz5nAjM+uKmT1NZyulyG01PmnmTPe5aoAeaqIw1JM9TVLLA3cTfulc/cY0i3r6tF2tjpZwa2uip4ZQRvXAfV/mFrazbTdXm0jHMF3e8XRMFc6E/O8s8/oDxl7fcsL7EI2H4oxQuSzvH2PQIl4E+cj4qzYUhGZX6gYrkErfPycZk31LIhuUbAXk2IajruaMh7AJEApJczSNtqmCo3EgPs/p5AC7+MjzvocdKQVW4K7QMCI3gre5WMe3szs7EhQ9PsicYqMuv8TUpDqMOXqWR5qebXs6cpF5tVOqbVa9tyCRzPwVQZodMbXHh8eq9fDi5vA7bYCmEjXmjr+nc3Rl+Cqbyct7tMFG+6UW0vwEY1OUJdfOT+7FyziLjCo6CfFEx0j+eZVkP7uvUDnUGzg6K7g2/k7cpiHhlUxQ2m+fKZvJZ9SNriszFl+FDVTNAf3TNO+j1p5sTBiasm6dGprOf8AKI7xEUv7NrdWLqW+y9+Z3tEUFv59Jk5r+vtFU9rGoqNNF98ADyLepq5Y0By6vwINjo4Py9zmTSZLPhrJktEt1Mq8bxI+ScdYDCybplFnYa3B28aE0W24AdaRbKSo+aWBzICS
    admin-user: AgBNup3OjxKtb0BHPt1ET1lr3bkYVDdkpe3Euk41ThIdLeZ87aHJceX11tvOddmYgv6hcGFqgBEtNsIkZFH3wRLZ8fjMFBGTjxS26XLZFPO/zBPEA+aEw6RG1J176ydjevV48B+B8cEMOQumOK5op49BskeAd9jevvdTh6uHFBxOkgnqxhWDpEuFDFphbsqBd2GI3CyPk/fhM7Q5fUCI6tkg6HQPxTIcn7WqqGr9AMl659xuJXAnYWLO6lP7Y8EpKXk9psNC2dvetA1Cr21RT70XQtcsJbv2EPNU50LJteGPvxcjmkHn4EZtVfzQCZg9iYiCRAhsAxK6k46BVY2etET08bppm72LWp94rd9NBYR6FsGEw9ho4HcYVvsyTBzEwXQv7pAw7CBUUZcYe8aRM9lD8Y9471YUlITfRRz5VSDDNFoBwRBY6AP136MN1wct5a8FoCbfRjV9uLCGU9AU5Z8gGcRe9m6TEadDg552n3iON2q4oHgAAE3dTNFiRCXYKvFHxLsZd8JCojv60+d2Thn68RbWWG+nUE6aW+fERYVxy3Gy6s20GwCCVIefWfuG8x14XIxEs0miuaeT1d9zUOo83C5S5Q0+Srp2PQ92UdgpTSGDJ/7IHOTQE2snC4iWz/n30Yoh973Okln6013NXGK2y6RHNM3juSalhe5DUCo6M/WYCIpx4wo9cN9uZiyd9mhcr86zpd8jwOE=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
    type: Opaque
